@startuml

title 后关联自动供码设计流程
autonumber

== 中城定时轮询供码 ==
中城服务器 -> 中城服务器 : 查询自动供码企业的所有产品id
中城服务器 -> 晶科redis : 根据产品id依次轮询自动供码企业所有产品的码包使用情况
alt 码包解密成功
    中城服务器 -> 晶科ftp服务器 : 删除码包
    中城服务器 -> 中城服务器 : 记录晶科使用码包记录,生成10万单位的码包
    中城服务器 -> 晶科redis : 生成码包对应的加密key, ftp下载路径等信息并存放入对应产品id下
else 码包解密失败
    中城服务器 -> 晶科ftp服务器 : 删除码包
    中城服务器 -> 中城服务器 : 记录晶科使用码包记录,生成码包
    中城服务器 -> 晶科redis : 生成码包对应的加密key并存放入对应产品id下
else 码包未被使用
    中城服务器 -> 晶科redis : 查询下一个产品id对应码包情况
end

== 尚浩使用码包 ==
尚浩工控机 -> 晶科redis : 查询对应产品id的码包状态和ftp地址信息
loop
alt 是否下载完毕
    尚浩工控机 -> 晶科ftp服务器 : 一次下载10万单位的码包
    alt 码包解密成功
        尚浩工控机 -> 晶科redis : 更新该码包对应状态和相关信息
    else 码包解密失败
        尚浩工控机 -> 晶科redis : 查询对应产品下一个码包的状态和ftp地址信息
        尚浩工控机 -> 晶科ftp服务器 : 一次下载10万单位的码包
    end
else
    尚浩工控机 -> 尚浩工控机 : 结束
end
end
@enduml


