spring:
  application:
    name: mynetty
  mail:
    host: smtp.exmail.qq.com
#    port: 465
    username: ww-1096
    password: 123456
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#    default-encoding: utf-8
#    ssl: true
#    auth: true
#    timeout: 5000
    smtp:
      socketFactory:
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
        port: 465
    ##REDIS配置
  redis:
    database: 11
    host: 172.16.38.197
    password: bili@2233
    pool:
      max-wait: 5000
      max-idle: 10
      min-idle: 10
      max-active: 50
    port: 6379
    timeout: 3000

  # Spring message
  messages:
    encoding: utf-8
    basename: i18n/messages
    cache-duration: 3600



  security:
    user:
      name: wrh
      password: 123456
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.16.38.108:3306/data_center?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1QWed$%&098pln@@_80
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
#      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCPpool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


server:
  port: 9988
  servlet:
    context-path: /mynetty

zipkin:
  serviceName: myzipkin
  url: http://127.0.0.1:9411
  connectTimeout: 6000
  readTimeout: 6000
  flushInterval: 1
  compressionEnabled: true


# logging
logging:
  path: logs
  level:
    com.wrh.mapper: debug
    org.springframework: warn
    com.wrh: info
    org.apache.ibatis.io.ResolverUtil: info

cq:
  key: aaabbbccc

redis:
  prefix: myown-

#原始数据kafka读取

  kafka:
    bootstrap-servers: 127.0.0.1:9092

    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
kafka:
  topic:
    group-id: default
    topic-name: default

param:
  juzhen1: 1,2,3
  juzhen2: 1.9,2.3,0.1
  list: aaa,bbb,ccc
  set: 111,222,333,111
  map1: '{"name":"zhangsan","sex":"male"}'
  map2: '{"math":"90","english":"85"}'






